fixed some routing on the readme file
opencdms/opencdms-test-data pull request #27
Opened 2022-09-08 14:28 UTC by marvelous-benji

This PR contains some fix to broken links on certain part of the readme files

2022-09-09 07:53 UTC, isedwards approved these changes

2022-09-11 07:48 UTC, isedwards requested changes
@marvelous-benji Could you separate the docs changes (issue #28) and the addition of GitHub actions (#19) into two separate PRs?  I'll also create issues that reference both.

2022-09-13 09:36 UTC, isedwards commented
@marvelous-benji could you create a new branch containing the first two commits from this PR so that we can get the docs changes merged and close issue #28?

Something like:
```
git checkout 6130e8fb984d8646a6d28e6fd7b84330398a4e34 -b docs_fix_links
git push docs_fix_links
```

2022-09-15 05:24 UTC, black-daemon commented
Hello @isedwards, I have done this. Thanks for heads up

2022-10-27 19:41 UTC, closed without merging